version: "3.3"

services:
  db:
    platform: linux/x86_64
    container_name: db
    # path配下のDockerfile読み込み
    build: ./docker/db
    # コンテナが落ちたら再起動する
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: jwt_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password # ユーザのパスワード
      MYSQL_ROOT_PASSWORD: password # ルートパスワード
    ports:
      - "3307:3306"
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d # MySQLの基本設定(文字化け対策)
      - ./log/mysql:/var/log/mysql # ログの保存
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    #command: mysqld --innodb_use_native_aio=0
    networks:
      - local-net

  # go app
  api:
    platform: linux/x86_64
    container_name: api
    tty: true
    env_file:
      - env_file.env
    depends_on:
      - db
    # path配下のDockerfile読み込み
    build: ./docker/api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/usr/src/server
    networks:
      - local-net

# コンテナ間で通信を行うためのネットワークブリッジ
networks:
  local-net:
    driver: bridge